.PHONY: test build gateway-test services-test web-build smoke docker-maintain docker-disk-expand

test: gateway-test services-test web-build

build: gateway-test services-build web-build

gateway-test:
	$(MAKE) -C gateway test

services-build:
	cd services/user-service && go build ./...
	cd services/audit-service && go build ./...
	cd services/workflow-service && go build ./...
	cd services/search-service && go build ./...
	cd services/notification-service && go build ./...
	cd services/file-service && go build ./...

services-test:
	cd services/user-service && go test ./...
	cd services/audit-service && go test ./...
	cd services/workflow-service && go test ./...
	cd services/search-service && go test ./...
	cd services/notification-service && go test ./...
	cd services/file-service && go test ./...

web-build:
	cd web && npm run build

smoke:
	./scripts/smoke-test.sh

docker-maintain:
	./scripts/docker-maintain.sh

docker-disk-expand:
	./scripts/docker-disk-expand.sh
